### ISSUE TITLE
App must target Android 14 (API level 34) or higher

### ISSUE THREAD

**Issue by silvioheinze** [luftdaten-at/luftdaten-app#13]
To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.
From Aug 31, 2024, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

Your highest non-compliant target API level is Android 13 (API level 33).

To ensure that you can continue to make updates to your app you must:

Update your app to target Android 14 (API level 34) or higher.
Publish a new version of your app to production. Before you do this, you can test your app using internal, closed, or open testing.

**Comment by silvioheinze** [comment]
<img width="904" alt="Bildschirmfoto 2024-08-01 um 14 44 22" src="https://github.com/user-attachments/assets/f4e382e1-eef1-4520-a1d5-fc875006d9b1">

Update Deadline: Nov 1, 2024 – Extension granted

**Comment by n11ik** [comment]
The qr_code_scanner [https://github.com/juliuscanute/qr_code_scanner] package requires a lower kotlin version as supported by flutter.
![Pasted image 20240919144306](https://github.com/user-attachments/assets/230ea3a9-9251-4e8d-9518-736b36a38bd3)
![Pasted image 20240919144352](https://github.com/user-attachments/assets/60ee1491-00cb-44bb-9069-b0d25d460aa8)

One solution is to use a different package for scanning qr codes.
